using System.Collections;
using System.Collections.Generic;
using DG.Tweening;
using UnityEngine;
using UnityEngine.EventSystems;
using static UICardCell;

public class UIDraggable : MonoBehaviour, IPointerDownHandler, IPointerUpHandler, IPointerClickHandler, IDragHandler
{
    public static bool ShouldBlockInput;
    public static bool IsDragPointerDown;
    public static bool ShouldSnapToCenter;

    public enum EFlipMode
    {
        None,
        OnStartDrag,
        OnEndDrag
    }

    public bool IsDragging { get; private set; }
    public bool IsDraggable = true;// { get; set; }

    protected bool pointerClickFlag;

    protected Vector2 clickPosition;
    private Vector2 mouseOffset;
    private float buffer = 10;
    protected float clickStartTime = -1;

    private float doubleClickTolerance = .3f;
    private float doubleClickStartTime = -1;

    private bool wasDraggedOutsideOfBuffer;

    private UICardCell originalParentCell;

    private List<UIHighlightableObject> highlightedObjects = new List<UIHighlightableObject>();

    public bool IsAnimateDragging { get; private set; }

    public bool ShouldAllowDropAnywhere = true;

    public EFlipMode FlipMode;

    [Space]
    [SerializeField] private RectTransform dontFlipArea;

    private bool shouldFlipOnClick;

    public virtual void OnPointerClick(PointerEventData eventData)
    {
        if (!GameManager.IN.IsPlayersTurn) return;

        float elapsedTimeSinceLastClick = Time.time - this.doubleClickStartTime;

        StopAllCoroutines();

        if (eventData.button == PointerEventData.InputButton.Left)
        {
            if (this.doubleClickStartTime > -1 && elapsedTimeSinceLastClick < this.doubleClickTolerance)
            {
                this.doubleClickStartTime = -1;
                OnDoubleClick();
            }
            else
            {
                this.doubleClickStartTime = Time.time;
                StartCoroutine(ResetDoubleClickTimer());
            }
        }
        else if (eventData.button == PointerEventData.InputButton.Right)
        {
            CancelDraggingItem();

            Debug.Log($"Right Click");
        }
    }

    private IEnumerator ResetDoubleClickTimer()
    {
        yield return new WaitForSeconds(this.doubleClickTolerance);
        this.doubleClickStartTime = -1;
    }

    public virtual void OnDoubleClick()
    {
        if (!GameManager.IN.IsPlayersTurn) return;

        //Debug.Log($"OnDoubleClick");

        //var cardFlip = this.GetComponent<UICardFlip>();
        //if (cardFlip != null)
        //    cardFlip.ToggleState();

        var card = this.GetComponent<Card>();

        UICardCloseUp.IN.Show(card);
    }

    public virtual void OnPointerDown(PointerEventData eventData)
    {
        if (!GameManager.IN.IsPlayersTurn) return;

        UIDraggable.IsDragPointerDown = true;

        if (eventData.button == PointerEventData.InputButton.Right)
        {
            CancelDraggingItem();
            return;
        }

        this.clickStartTime = Time.time;
        this.clickPosition = GetMousePosition();

        if (ShouldSnapToCenter)
        {
            this.mouseOffset = Vector2.zero;
        }
        else
        {
            UIDragOverlay.IN.DummyObj.transform.position = this.transform.position;
            this.mouseOffset = (Vector2)UIDragOverlay.IN.DummyObj.transform.localPosition - this.clickPosition;
        }

        if (!this.IsDragging)
        {
            this.pointerClickFlag = true;
            this.wasDraggedOutsideOfBuffer = false;
        }

        if (this.dontFlipArea != null)
            this.shouldFlipOnClick = !RectTransformUtility.RectangleContainsScreenPoint(this.dontFlipArea, eventData.position);
    }

    public virtual void OnPointerUp(PointerEventData eventData)
    {
        if (!GameManager.IN.IsPlayersTurn) return;

        UIDraggable.IsDragPointerDown = false;

        if (eventData.button == PointerEventData.InputButton.Right)
        {
            CancelDraggingItem();
            return;
        }

        this.pointerClickFlag = false;
        this.shouldFlipOnClick = false;

        if (this.IsDragging && this.wasDraggedOutsideOfBuffer)
        {
            this.wasDraggedOutsideOfBuffer = false;
            StopDraggingItem(eventData);
        }
    }

    protected bool CheckStartDrag()
    {
        if (this.pointerClickFlag)
        {
            var dragItemPos = GetMousePosition();

            float delta = Vector2.Distance(this.clickPosition, dragItemPos);
            float elapsedTime = Time.time - this.clickStartTime;

            bool isDraggedOutOfBuffer = delta > this.buffer;

            if (isDraggedOutOfBuffer)
            {
                this.pointerClickFlag = false;
                BeginDraggingItem();
            }
        }

        return !this.pointerClickFlag;
    }

    protected Vector2 GetMousePosition()
    {
        var mousePos = UIDragOverlay.IN.Camera.WorldToScreenPoint(Input.mousePosition);

        RectTransformUtility.ScreenPointToLocalPointInRectangle(UIDragOverlay.IN.Overlay, mousePos, UIDragOverlay.IN.Camera, out var dragItemPos);

        return dragItemPos;
    }

    protected virtual void LateUpdate()
    {
        if (!CheckStartDrag() || this.IsAnimateDragging) return;

        if (this.IsDragging)
        {
            var dragItemPos = GetMousePosition();

            float delta = Vector2.Distance(this.clickPosition, dragItemPos);

            if (delta > this.buffer)
                this.wasDraggedOutsideOfBuffer = true;

            HighlightItemsUnderCursor();

            this.transform.localPosition = dragItemPos + this.mouseOffset;
        }
    }

    private void HighlightItemsUnderCursor()
    {
        var results = GameObjectUnderPointer();

        //string debugString = string.Empty;

        List<UIHighlightableObject> currentItemsUnderCursor = new List<UIHighlightableObject>();

        foreach (var result in results)
        {
            //debugString += $"{result.gameObject.name}, ";

            var highlight = result.gameObject.GetComponent<UIHighlightableObject>();

            if (highlight != null)
            {
                if (!this.highlightedObjects.Contains(highlight))
                {
                    this.highlightedObjects.Add(highlight);
                    highlight.Show();
                }

                currentItemsUnderCursor.Add(highlight);
            }
        }

        //Debug.Log($"under cursor = {debugString}");

        List<UIHighlightableObject> listCopy = new List<UIHighlightableObject>(this.highlightedObjects);

        //when item is not longer under cursor, hide and remove from list
        foreach (var item in listCopy)
        {
            if (!currentItemsUnderCursor.Contains(item))
            {
                item.Hide();
                this.highlightedObjects.Remove(item);
            }
        }
    }

    private void HideItemHighlights()
    {
        foreach (var item in this.highlightedObjects)
        {
            item.Hide();
        }

        this.highlightedObjects.Clear();
    }

    protected virtual void BeginDraggingItem()
    {
        //Debug.Log($"BeginDraggingItem()");

        if (UIDraggable.ShouldBlockInput || !this.IsDraggable || this.IsDragging) return;

        var cell = this.transform.GetComponentInParent<UICardCell>();
        //if (cell == null || (cell.PlayerType != GameManager.IN.CurrentPlayer && !this.IsAnimateDragging)) return;
        if (cell == null && !this.ShouldAllowDropAnywhere) return;

        UIDraggable.ShouldBlockInput = true;
        this.IsDragging = true;

        if (cell != null)
        {
            this.originalParentCell = cell;

            if (cell.CellType == ECellType.Deck)
            {
                var deck = cell.GetComponent<UIDeck>();
                var card = this.GetComponent<Card>();
                deck.RemoveCardFromDeck(card);
            }
        }

        if (this.shouldFlipOnClick)
        {
            this.shouldFlipOnClick = false;
            var cardFlip = this.GetComponent<UICardFlip>();

            if (cardFlip != null && this.FlipMode == EFlipMode.OnStartDrag && cardFlip.CardFlipState == UICardFlip.ECardFlipState.Back)
                cardFlip.SetAnimState(UICardFlip.ECardFlipState.FlipToFront);
        }

        UIDragOverlay.IN.SetDraggingItem(this.transform);
        //var destScale = Vector3.Min(this.transform.localScale, Vector3.one);
        //this.transform.DOScale(destScale, .1f);
    }

    public void SetOriginalParentCell()
    {
        var cell = this.transform.GetComponentInParent<UICardCell>();
        this.originalParentCell = cell;
    }

    protected virtual void StopDraggingItem(PointerEventData eventData)
    {
        UIDraggable.ShouldBlockInput = false;
        this.IsDragging = false;

        HideItemHighlights();

        UIDragOverlay.IN.SetVisible(false);

        var cell = UICardCell.GetCellAtPosition(this.transform.position);

        if (cell != null)
        {
            if (cell.CellType == ECellType.Discard)
            {
                var card = this.GetComponent<Card>();

                if (card.ParentDeck != null)
                    card.ParentDeck.AddCardToDeck(card);
            }
            else
                cell.HandleDrop(this.originalParentCell);
        }
        else
        {
            var hand = UIHand.GetUIHandAtPosition(this.transform.position);

            if (hand != null)
            {
                hand.HandleDrop(this.originalParentCell);
            }
            else
            {
                if (!this.ShouldAllowDropAnywhere)
                    this.originalParentCell.ReturnCardToCell();
                else
                {
                    //this.transform.SetParent(GameManager.IN.CurrentPlayerBoard.transform);

                    SetParentToDroppableObject();

                    if (this.shouldFlipOnClick)
                    {
                        this.shouldFlipOnClick = false;
                        var cardFlip = this.GetComponent<UICardFlip>();

                        if (cardFlip != null && this.FlipMode == EFlipMode.OnEndDrag && cardFlip.CardFlipState == UICardFlip.ECardFlipState.Back)
                            cardFlip.SetAnimState(UICardFlip.ECardFlipState.FlipToFront);
                    }
                }
            }
        }
    }

    private void SetParentToDroppableObject()
    {
        var results = GameObjectUnderPointer();

        foreach (var result in results)
        {
            var droppable = result.gameObject.GetComponentInParent<UIDroppableArea>();

            if (droppable != null)
            {
                this.transform.SetParent(droppable.DropArea);
                this.transform.DOScale(droppable.transform.localScale, .1f);
                break;
            }
        }
    }

    public virtual void CancelDraggingItem()
    {
        //Debug.Log($"CancelDraggingItem");

        if (this.IsDragging)
        {
            if (!this.ShouldAllowDropAnywhere)
                this.originalParentCell.ReturnCardToCell();

            UIDraggable.ShouldBlockInput = false;
            UIDraggable.IsDragPointerDown = false;
            this.IsDragging = false;
            HideItemHighlights();
        }
    }

    public static List<RaycastResult> GameObjectUnderPointer()
    {
        return GameObjectAtPosition(Input.mousePosition);
    }

    public static List<RaycastResult> GameObjectAtPosition(Vector3 inPosition)
    {
        var pointerData = new PointerEventData(EventSystem.current)
        {
            pointerId = -1
        };

        pointerData.position = inPosition;

        var raycastResults = new List<RaycastResult>();
        EventSystem.current.RaycastAll(pointerData, raycastResults);

        return raycastResults;
    }

    //this is to fix a bug that happens with ScrollRect interfering with OnPointerUp()
    public void OnDrag(PointerEventData eventData) { }

    public void AnimateTo(Vector3 inDestPosition, float inTweenDuration = .5f, float inDelayAtEnd = 0)
    {
        this.IsAnimateDragging = true;

        BeginDraggingItem();

        UIDraggable.ShouldBlockInput = true;

        this.transform.DOMove(inDestPosition, inTweenDuration, false).SetEase(Ease.InOutSine).OnComplete(() =>
        {
            this.transform.position = inDestPosition;

            if (inDelayAtEnd == 0)
            {
                StopDraggingItem(null);
                this.IsAnimateDragging = false;
            }
            else
            {
                this.gameObject.SetActive(true);//not sure if necessary, but prevents an error
                StartCoroutine(DelayedAnimCompleteCo(inDelayAtEnd));
            }
        });
    }

    private IEnumerator DelayedAnimCompleteCo(float inDelay)
    {
        yield return new WaitForSeconds(inDelay);

        StopDraggingItem(null);
        this.IsAnimateDragging = false;
    }
}